"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import socket
import time
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET")

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")

CORS_ALLOW_CREDENTIALS = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True')
if DEBUG.lower() in ('false', '0') or not DEBUG:
    DEBUG = False
else:
    DEBUG = True

DB_ADDRESS = ''

while not DB_ADDRESS:
    try:
        DB_ADDRESS = socket.gethostbyname(os.environ.get('DB_HOST', ''))
    except Exception as e:
        print('DB Unavailable')
        print(os.environ.get('DB_HOST', ''))
        time.sleep(10)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# Use SSL
SPSH = os.environ.get('SECURE_PROXY_SSL_HEADER', 'False')
if SPSH.lower() not in ('false', '0'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True')
if CSRF_COOKIE_SECURE.lower() in ('false', '0') or not CSRF_COOKIE_SECURE:
    CSRF_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework_simplejwt", #   Для авторизации по JWT токенам
    "rest_framework_simplejwt.token_blacklist", #   Отображение токенов в админке
    "rest_framework",   # DRF
    "drf_yasg", # swagger
    'corsheaders',  #   для задания цорсов (cors)
    'quiz.apps.QuizConfig',   #   основное приложэние
    'accounts.apps.AccountsConfig',   #   кастомные аккаунты пользаков
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'accounts' / 'templates',
            BASE_DIR / 'quiz' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
     #   'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': os.environ.get('DB_DRIVER'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': DB_ADDRESS,
        'PORT': os.environ.get('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# media and static files

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PREFFIX_PATH=os.getenv("PREFIX_PATH", "")

if PREFFIX_PATH != "" and PREFFIX_PATH[-1] != "/":
    PREFFIX_PATH += "/"
MEDIA_URL = f'{PREFFIX_PATH}media/'

STATIC_URL = f'{PREFFIX_PATH}static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_FILES_DIRS = [
    BASE_DIR / "shortener" / "static"
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'

# Модель пользователей по умолчанию
AUTH_USER_MODEL = "accounts.CustomUser"

# Адреса входа и выхода
if PREFFIX_PATH:
    LOGIN_REDIRECT_URL = f"{PREFFIX_PATH}"
    LOGOUT_REDIRECT_URL = f"{PREFFIX_PATH}"
    LOGIN_URL = f"{PREFFIX_PATH}/login"        # URL страницы с формой входа
    LOGIN_ERROR_URL = f"{PREFFIX_PATH}/login-error/"
else:
    LOGIN_REDIRECT_URL = "/"
    LOGOUT_REDIRECT_URL = "/"
    LOGIN_URL = '/login'        # URL страницы с формой входа
    LOGIN_ERROR_URL = '/login-error/'


# DRF
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
    "rest_framework_simplejwt.authentication.JWTAuthentication",
    "rest_framework.authentication.BasicAuthentication",
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv("THROTTLE_RATE_ANON", '5000/day'),
        'user': os.getenv("THROTTLE_RATE_USER", '20000/day'),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    #'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DATE_FORMAT': "%d.%m.%Y",
    'DATETIME_FORMAT': "%d.%m.%y %H:%M:%S",
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # )
}

SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {
      'Basic': {
            'type': 'basic'
      },
      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
      }
   }
}

# JWT
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY", None)
JWT_VERIFYING_KEY = os.getenv("JWT_VERIFYING_KEY", None)

SIMPLE_JWT = {
   "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME", 3))),
   "REFRESH_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("REFRESH_TOKEN_LIFETIME", 15))),
   "ROTATE_REFRESH_TOKENS": True,
}

if 'rs' in JWT_ALGORITHM.lower() and JWT_SIGNING_KEY and JWT_VERIFYING_KEY:
   SIMPLE_JWT["ALGORITHM"] = JWT_ALGORITHM
   SIMPLE_JWT["SIGNING_KEY"] = JWT_SIGNING_KEY
   SIMPLE_JWT["VERIFYING_KEY"] = JWT_VERIFYING_KEY
elif 'hs' in JWT_ALGORITHM.lower():
   SIMPLE_JWT["ALGORITHM"] = JWT_ALGORITHM
